### ISSUE TITLE
CI publishing failed

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-mtl#402]
Looks like this repo is not set up for CI release, as there is no sonatype username or password.
```
  env:
    PGP_PASSPHRASE: 
    SONATYPE_PASSWORD: 
    SONATYPE_USERNAME: 
    PGP_SECRET: ***
    GITHUB_TOKEN: ***
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.312-7/x64
```
https://github.com/typelevel/cats-mtl/runs/5082449910?check_suite_focus=true#step:13:1

This will be fixed in:
- https://github.com/typelevel/governance/issues/23
